"""empty message

Revision ID: d6a976b25c55
Revises: a6e934d8789e
Create Date: 2025-04-05 13:25:16.829347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a976b25c55'
down_revision: Union[str, None] = 'a6e934d8789e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('session_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'session_id')
    # ### end Alembic commands ###
