"""add status column to feedback

Revision ID: ddb87b4e387a
Revises: 61dbe5933e8e
Create Date: 2025-07-26 15:28:16.110884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb87b4e387a'
down_revision: Union[str, None] = '61dbe5933e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('AI_ACCURACY', 'EMOTION_REPORT', 'INFORMATIVE', 'URGENT', 'urgent', name='notificationtype_old'),
               type_=sa.Enum('AI_ACCURACY', 'EMOTION_REPORT', 'INFORMATIVE', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('AI_ACCURACY', 'EMOTION_REPORT', 'INFORMATIVE', name='notificationtype'),
               type_=postgresql.ENUM('AI_ACCURACY', 'EMOTION_REPORT', 'INFORMATIVE', 'URGENT', 'urgent', name='notificationtype_old'),
               existing_nullable=False)
    # ### end Alembic commands ###
